#COMPONENT_PRIV_INCLUDEDIRS=.

#COMPONENT_EXTRA_CLEAN:

TIMESTAMP	=$(shell date +%s)
#COMPONENT_ADD_LDFLAGS=-Xlinker -gc-sections,--defsym,LDTIMESTAMP=$(TIMESTAMP) -lmain
COMPONENT_ADD_LDFLAGS=-Xlinker --defsym -Xlinker LDTIMESTAMP=$(TIMESTAMP) -lmain
